### ISSUE TITLE
This list_tests.py file is not in the project. What should I do?

### ISSUE THREAD

**Issue by longbao8** [alniniclas/junit-to-jmh#1]
Can it be convenient to tell me how to do it?

**Comment by alniniclas** [comment]
Hi,

The [list_tests.py](https://github.com/alniniclas/junit-to-jmh-experiment/blob/master/scripts/gradle/list_tests.py) script is not in this repo, but in a separate repo called [junit-to-jmh-experiment](https://github.com/alniniclas/junit-to-jmh-experiment).

If you're trying to create a list of tests to give as input to ju2jmh, you can also create it manually by making a text file and putting the names of the test classes to generate benchmarks from on separate lines, like this:
```
com.example.FooTest
com.example.BarTest
com.example.BazTest
```

**Comment by longbao8** [comment]
When I run:
` ./gradlew converter:run --args="/junit-to-jmh-experiment/src/test/java/ /junit-to-jmh-experiment/build/classes/java/test/ /junit-to-jmh-experiment/src/jmh/java/ --class-names-file=/junit-to-jmh-experiment/test-classes.txt"`

This will produce an error:Execution failed for task ':converter:compileJava'.
For example:
Error: The orElseThrow method in the class java. util.Optional<T> cannot 
 be applied to the given type;
It is mentioned later that the actual parameter list and the formal parameter list have different lengths
There are also methods where references are invalid, and where symbols cannot be found
Hope to help me with the problem😭😭

**Comment by alniniclas** [comment]
What version of Java are you using? I believe at least Java 11 is needed for running the tool.

**Comment by longbao8** [comment]
> What version of Java are you using? I believe at least Java 11 is needed for running the tool.


I used the java14 version. I ran commands on the junit to jmh project and also reported many errors.
the command:
`./gradlew converter:run --args="/samples/src/test/java/ /samples/build/classes/java/test/ /samples/src/jmh/java/ --class-names-file=/samples/test-classes.txt"`
The content of the test-classes txt is se.chalmers.ju2jmh.samples.HelloTest

**Comment by alniniclas** [comment]
Can you post the full text of the error messages you're getting (or the full text of some of them, if you're getting a lot of errors that are saying the same thing)?

**Comment by longbao8** [comment]
> Task :converter:compileJava FAILED
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\Converter.java:128: Error: The orElseThrow method in the class java. util.Optional cannot be applied to the given type;
            String benchmarkClassName = benchmarkClass.getFullyQualifiedName().orElseThrow();
                                                                              ^
  need: java.util.function.Supplier<? extends X>
  find: No parameters
  Reason: Unable to infer type variable X
(The length of the actual parameter list is different from that of the formal parameter list)
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\Converter.java:149:Error: The orElseThrow method in the class java. util.Optional cannot be applied to the given type;
                                    .orElseThrow());
                                    ^
  need: java.util.function.Supplier<? extends X>
  find: No parameters
 Reason: Unable to infer type variable X
(The length of the actual parameter list is different from that of the formal parameter list)
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\Converter.java:177:Error: The orElseThrow method in the class java. util.Optional cannot be applied to the given type;
                                    .orElseThrow());
                                    ^
  need: java.util.function.Supplier<? extends X>
  find: No parameters
 Reason: Unable to infer type variable X
(The length of the actual parameter list is different from that of the formal parameter list)
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\Converter.java:182: Error: The orElseThrow method in the class java. util.Optional cannot be applied to the given type;
            compilationUnits.put(className, testClassSource.findCompilationUnit().orElseThrow());
                                                                                 ^
  need: java.util.function.Supplier<? extends X>
  find: No parameters
 Reason: Unable to infer type variable X
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\Converter.java:209:Error: symbol not found
                .collect(Collectors.toUnmodifiableList());
                                   ^
  symbol:   method toUnmodifiableList()
  position: class java.util.stream.Collectors
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\Converter.java:208: Error: Invalid method reference
                .map(Path::of)
                     ^
  symbol not found
  symbol:   method of()
  position: interface java.nio.file.Path
D:\textbook\Study\Project\junit-to-jmh\converter\src\main\java\se\chalmers\ju2jmh\JU4BenchmarkFactory.java:113: Error: Invalid method reference
                .map(NodeWithName::getNameAsString)
                     ^
  Cannot reference a non static method getNameAsString() from a static context


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':converter:compileJava'.
> java.lang.NullPointerException

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
4 actionable tasks: 1 executed, 3 up-to-date

I encountered many errors, such as: no parameters, no symbols, invalid method references.
These errors also occur when I am experimenting on the junit to jmh project.
I feel uncomfortable. I don't know how to use this tool. It just doesn't work.😥😥

**Comment by alniniclas** [comment]
Thanks! Just to be sure, could you also check and post the output of running `./gradlew --version`?

**Comment by longbao8** [comment]
> Thanks! Just to be sure, could you also check and post the output of running `./gradlew --version`?

the output of running ./gradlew --version
PS D:\textbook\Study\Project\junit-to-jmh> ./gradlew --version

------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          14.0.2 (Oracle Corporation 14.0.2+12-46)
OS:           Windows 10 10.0 amd64

Thanks for reminding! After I modified the jvm version of gradle, an error was reported when I ran the command
> Task :converter:run FAILED
java.io.FileNotFoundException: Output directory \samples\src\jmh\java does not exist

The sample/src/jmh does exist in the project, but an error is reported😑😑

**Comment by alniniclas** [comment]
Is `./gradlew converter:run --args="/samples/src/test/java/ /samples/build/classes/java/test/ /samples/src/jmh/java/ --class-names-file=/samples/test-classes.txt"` still the command you're running? If it is, then I think your paths are incorrect. `/samples/src/test/java/`, `/samples/build/classes/java/test/`, `/samples/src/jmh/java/`, and `/samples/test-classes.txt` are all absolute paths, but I think what you're trying to do is use relative paths. Try removing the `/` from the start of all of the paths to turn them into relative paths (so `samples/src/test/java/`, `samples/build/classes/java/test/`, `samples/src/jmh/java/`, and `samples/test-classes.txt`) and then see if the command works:

```
./gradlew converter:run --args="samples/src/test/java/ samples/build/classes/java/test/ samples/src/jmh/java/ --class-names-file=samples/test-classes.txt"
```

**Comment by longbao8** [comment]
> Is `./gradlew converter:run --args="/samples/src/test/java/ /samples/build/classes/java/test/ /samples/src/jmh/java/ --class-names-file=/samples/test-classes.txt"` still the command you're running? If it is, then I think your paths are incorrect. `/samples/src/test/java/`, `/samples/build/classes/java/test/`, `/samples/src/jmh/java/`, and `/samples/test-classes.txt` are all absolute paths, but I think what you're trying to do is use relative paths. Try removing the `/` from the start of all of the paths to turn them into relative paths (so `samples/src/test/java/`, `samples/build/classes/java/test/`, `samples/src/jmh/java/`, and `samples/test-classes.txt`) and then see if the command works:
> 
> ```
> ./gradlew converter:run --args="samples/src/test/java/ samples/build/classes/java/test/ samples/src/jmh/java/ --class-names-file=samples/test-classes.txt"
> ```

Thank you for your warm answer. I can run successfully using the absolute path.If there are any questions, I am humbly asking you!🌹🌹🌹

**Comment by alniniclas** [comment]
Glad to hear it finally worked! Feel free to reach out again if you run into more issues! 🙂
